const fs = require("fs");
const path = require("path");

const PLUGIN_DIR = path.join(__dirname, "plugin");
const BODY_PATH = path.join(PLUGIN_DIR, "apply-body.js");
const CODE_PATH = path.join(PLUGIN_DIR, "code.js");
const VARIABLES_PATH = path.join(__dirname, "variables.json");
const COMPONENTS_DIR = path.join(__dirname, "components");

function readJsonOrNull(filePath) {
	if (!fs.existsSync(filePath)) return null;
	return JSON.parse(fs.readFileSync(filePath, "utf8"));
}

function loadComponents() {
	const components = {};
	if (!fs.existsSync(COMPONENTS_DIR)) return components;
	for (const file of fs.readdirSync(COMPONENTS_DIR).sort()) {
		if (!file.endsWith(".json")) continue;
		const name = file.replace(/\.json$/, "");
		components[name] = readJsonOrNull(path.join(COMPONENTS_DIR, file));
	}
	return components;
}

function generatePlugin() {
	const body = fs.readFileSync(BODY_PATH, "utf8");
	const variables = readJsonOrNull(VARIABLES_PATH);
	const components = loadComponents();
	const code = `// AUTO-GENERATED by scripts/figma/generate-plugin.js — do not edit.
const VARIABLES = ${JSON.stringify(variables, null, "\t")};
const COMPONENTS = ${JSON.stringify(components, null, "\t")};
const CARD_COMPONENT = COMPONENTS.card || null;

${body}

(async () => {
	const result = await runDeckToolSync(figma.command || "all");
	figma.closePlugin(JSON.stringify(result));
})();
`;
	fs.mkdirSync(PLUGIN_DIR, { recursive: true });
	fs.writeFileSync(CODE_PATH, code);
	return CODE_PATH;
}

module.exports = { generatePlugin };

if (require.main === module) {
	generatePlugin();
	console.log("Updated scripts/figma/plugin/code.js");
}
