const fs = require("fs");
const path = require("path");

const PLUGIN_DIR = path.join(__dirname, "plugin");
const BODY_PATH = path.join(PLUGIN_DIR, "apply-body.js");
const CODE_PATH = path.join(PLUGIN_DIR, "code.js");
const VARIABLES_PATH = path.join(__dirname, "variables.json");
const COMPONENTS_DIR = path.join(__dirname, "components");
const TEMPLATES_DIR = path.join(__dirname, "templates");

function readJsonOrNull(filePath) {
	if (!fs.existsSync(filePath)) return null;
	return JSON.parse(fs.readFileSync(filePath, "utf8"));
}

function loadJsonDir(dir) {
	const out = {};
	if (!fs.existsSync(dir)) return out;
	for (const file of fs.readdirSync(dir).sort()) {
		if (!file.endsWith(".json")) continue;
		const name = file.replace(/\.json$/, "");
		out[name] = readJsonOrNull(path.join(dir, file));
	}
	return out;
}

function loadComponents() {
	return loadJsonDir(COMPONENTS_DIR);
}

function loadTemplates() {
	return loadJsonDir(TEMPLATES_DIR);
}

function generatePlugin() {
	const body = fs.readFileSync(BODY_PATH, "utf8");
	const variables = readJsonOrNull(VARIABLES_PATH);
	const components = loadComponents();
	const templates = loadTemplates();
	const code = `// AUTO-GENERATED by scripts/figma/generate-plugin.js — do not edit.
const VARIABLES = ${JSON.stringify(variables, null, "\t")};
const COMPONENTS = ${JSON.stringify(components, null, "\t")};
const TEMPLATES = ${JSON.stringify(templates, null, "\t")};
const CARD_COMPONENT = COMPONENTS.card || null;

${body}

(async () => {
	const result = await runDeckToolSync(figma.command || "all");
	figma.closePlugin(JSON.stringify(result));
})();
`;
	fs.mkdirSync(PLUGIN_DIR, { recursive: true });
	fs.writeFileSync(CODE_PATH, code);
	return CODE_PATH;
}

module.exports = { generatePlugin };

if (require.main === module) {
	generatePlugin();
	console.log("Updated scripts/figma/plugin/code.js");
}
